# Aponta para o dispositivo de hardware no kernel do CM5 (BCM2711)
watchdog-device = /dev/watchdog

# Se o sistema ficar 10 segundos sem responder, reinicia a placa na força física
watchdog-timeout = 10

# Tempo de intervalo em que o daemon diz "Estou vivo" para o chip
interval = 2

# Opcional: Reinicia a placa se o sistema travar por falta de memória RAM!
# max-load-1 = 24
