#!/bin/sh

. /usr/bin/jupiter-common
    
start() {
    jupiter_mkdirs
    jupiter_log init "starting"

    hwclock -s

    /usr/bin/jupiter-gpio-init
    /usr/bin/jupiter-i2c init || jupiter_log init "i2c initialization failed"
    /usr/bin/jupiter-network-init
    /usr/bin/jupiter-services start

    jupiter_log init "started"
}

stop() {
    jupiter_log init "stopping"
    /usr/bin/jupiter-services stop
    jupiter_log init "stopped"
}
restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
