[Interface]
Address = 10.100.0.18/32
PrivateKey = 2H7feXB0xyYLZVeL7PYiibu8Hx4zg1nLYNw2wVDDP2g=

[Peer]
PublicKey = tV+J1k9TSkTEhgZlWwA/+JJLMz0Mvu/8C/42JNrq+G4=
Endpoint = 129.121.45.199:51820
AllowedIPs = 10.100.0.0/24
PersistentKeepalive = 25
