[Interface]
Address = 10.100.0.22/32
PrivateKey = 8O4K0liDBOsvg2REV4jAX6NKDuo90HW8Xhq1BFhGfFU=

[Peer]
PublicKey = tV+J1k9TSkTEhgZlWwA/+JJLMz0Mvu/8C/42JNrq+G4=
Endpoint = 129.121.45.199:51820
AllowedIPs = 10.100.0.0/24
PersistentKeepalive = 25
