[Interface]
Address = 10.100.1.3/32
PrivateKey = 0BZABTSw0Gk/N2jR4mTD7pEZTIjW1+Xt1CgA0BmMmWg=

[Peer]
PublicKey = eRNAYgqQfOfeh6DHttkDbCjIwt0Mui6AcukHPmKC83I=
Endpoint = 129.121.45.199:51821
AllowedIPs = 10.100.1.0/24
PersistentKeepalive = 25
